title: Martijn's Huis

resources:
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/gauge-card.js?v=2
    type: js
  - url: /local/mini-media-player/mini-media-player.js?v=0.8.3
    type: module
  - url: /local/thermostat-card.js
    type: module
  - url: /local/simple-thermostat.js
    type: module
  - url: /local/card-modder.js
    type: module
  - url: /local/card-tools.js
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js
    type: module
  - url: /local/entity-attributes-card.js
    type: js
  - url: /local/jukebox.js
    type: module
  - url: /local/tiles-card.js
    type: js
  - url: /local/state-switch.js
    type: js
  - url: /local/mini-graph-card-bundle.js
    type: module
  - url: /local/button-card.js
    type: module
  - url: /local/compact-custom-header.js
    type: module
  - url: /local/bar-card.js
    type: js
  - url: /local/monster-card.js
    type: js
  - url: /local/postnl-card.js
    type: module

background: center / cover no-repeat url("/local/back.png") fixed
views:
  - badges: []
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        voice: hidden
        notifications: hide
      - type: vertical-stack
        cards:
          - type: 'custom:card-modder'
            style:
              border-radius: 20px
              background-image: url("/local/cardbackK.png")
              background-repeat: no-repeat
              background-color: rgba(50,50,50,0.3)
              background-size: 100% 68px
              border: solid 1px rgba(100,100,100,0.3)
              color: "#999999"
              box-shadow: 3px 3px rgba(0,0,0,0.4)
            card:
              type: picture-elements
              image: /local/webtijn.jpg
              elements:
                - type: state-icon
                  entity: sensor.iphone_van_martijn_battery_level_2
                  style: {color: white, left: 5%, top: 94%}
                - type: state-label
                  entity: sensor.iphone_van_martijn_battery_level_2
                  style: {color: white, left: 14%, top: 94%}
                - type: state-icon
                  entity: sensor.postnl
                  style: {color: white, left: 25%, top: 94%}
                - type: state-label
                  entity: sensor.postnl
                  style: {color: white, left: 40%, top: 94%}
                - type: state-icon
                  entity: sensor.naar_huis
                  style: {color: white, left: 58%, top: 94%}
                - type: state-label
                  entity: sensor.naar_huis
                  style: {color: white, left: 68%, top: 94%}
                - type: state-icon
                  entity: sensor.naar_ellen
                  style: {color: white, left: 80%, top: 94%}
                - type: state-label
                  entity: sensor.naar_ellen
                  style: {color: white, left: 92%, top: 94%}
                - type: state-label
                  entity: sensor.martijn_status
                  style: {color: white, left: 93%, top: 89%}
                - type: state-label
                  entity: sensor.google_geocode
                  style: {color: white, left: 38%, top: 89%}
          - type: 'custom:card-modder'
            style:
              border-radius: 20px
              background-image: url("/local/cardbackK.png")
              background-repeat: no-repeat
              background-color: rgba(50,50,50,0.3)
              background-size: 100% 68px
              border: solid 1px rgba(100,100,100,0.3)
              color: "#999999"
              box-shadow: 3px 3px rgba(0,0,0,0.4)
            card:
              type: custom:calendar-card
              name: Agenda
              numberOfDays: 7
              showProgressBar: false
              entities:
                - calendar.martijn_kalf_gmail_com
                - calendar.ellen_en_martijn
                - calendar.https_www_avalex_nl_ical_0503200000109880
              showColors: true
    icon: 'mdi:account'
    title: Martijn

  - badges: []
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        voice: hidden
        notifications: hide
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: 'custom:card-modder'
                style:
                  border-radius: 20px
                  background-image: url("/local/cardbackK.png")
                  background-repeat: no-repeat
                  background-color: rgba(50,50,50,0.3)
                  background-size: 100% 68px
                  border: solid 1px rgba(100,100,100,0.3)
                  color: "#999999"
                  box-shadow: 3px 3px rgba(0,0,0,0.4)
