- platform: template
  sensors:
    alarm_tijd:
      friendly_name: 'Tijd'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmuur") | int, states("input_number.alarmminuten") | int) }}'
